// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-6bcXDkNpHjVncvWIzb8GclwfXP5bS2Q',
    appId: '1:934451717707:web:8ecbe6933c42f07776cfce',
    messagingSenderId: '934451717707',
    projectId: 'another-monday',
    authDomain: 'another-monday.firebaseapp.com',
    storageBucket: 'another-monday.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpPKX11BJYlNKUUzujwUy_D9TVVP1rzLE',
    appId: '1:934451717707:android:25eff71cd3fec78176cfce',
    messagingSenderId: '934451717707',
    projectId: 'another-monday',
    storageBucket: 'another-monday.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRdb5V5sde0CXe57QCVBZu-kC8oA5EIfo',
    appId: '1:934451717707:ios:2b0582e574e5e52c76cfce',
    messagingSenderId: '934451717707',
    projectId: 'another-monday',
    storageBucket: 'another-monday.firebasestorage.app',
    iosClientId: '934451717707-r9ldos2h3i7b79g7fkcvvm08ceb5tal2.apps.googleusercontent.com',
    iosBundleId: 'com.wavy.wavy',
  );
}
